export const REQUEST_PROJECT_MEMBER = 'REQUEST_PROJECT_MEMBER'
export const PROJECT_MEMBER_FETCH_SUCCESSFULL = 'PROJECT_MEMBER_FETCH_SUCCESSFULL'
export const PROJECT_MEMBER_FETCH_FAIL = 'PROJECT_MEMBER_FETCH_FAIL'
export const PROJECT_MEMBER_HANDLE_ERROR = 'PROJECT_MEMBER_HANDLE_ERROR'

export const PROJECT_MEMBER_ASSIGN = 'PROJECT_MEMBER_ASSIGN'
export const PROJECT_MEMBER_UNASSIGN = 'PROJECT_MEMBER_UNASSIGN'