export const REQUEST_LIST_USER = 'REQUEST_LIST_USER'
export const LIST_USER_FETCH_SUCCESSFULL = 'LIST_USER_FETCH_SUCCESSFULL'
export const LIST_USER_FETCH_FAIL = 'LIST_USER_FETCH_FAIL'
export const LIST_USER_HANDLE_ERROR = 'LIST_USER_HANDLE_ERROR'
