export const REQUEST_PROJECT_CREATED = 'REQUEST_PROJECT_CREATED'
export const FETCH_SUCCESSFULL = 'FETCH_SUCCESSFULL'
export const FETCH_FAIL = 'FETCH_FAIL'
export const HANDLE_ERROR = 'HANDLE_ERROR'
