export const REQUEST_PROJECT_ASSIGN = 'REQUEST_PROJECT_ASSIGN'
export const PROJECT_ASSIGN_FETCH_SUCCESSFULL = 'PROJECT_ASSIGN_FETCH_SUCCESSFULL'
export const PROJECT_ASSIGN_FETCH_FAIL = 'PROJECT_ASSIGN_FETCH_FAIL'
export const PROJECT_ASSIGN_HANDLE_ERROR = 'PROJECT_ASSIGN_HANDLE_ERROR'
