export const REQUEST_PROJECT_CREATED = 'REQUEST_PROJECT_CREATED'
export const PROJECT_CREATED_FETCH_SUCCESSFULL = 'PROJECT_CREATED_FETCH_SUCCESSFULL'
export const PROJECT_CREATED_FETCH_FAIL = 'PROJECT_CREATED_FETCH_FAIL'
export const PROJECT_CREATED_HANDLE_ERROR = 'PROJECT_CREATED_HANDLE_ERROR'

export const PROJECT_CREATED_CREATE_SUCCESSFULL = 'PROJECT_CREATED_CREATE_SUCCESSFULL'
export const PROJECT_CREATED_DELETE_SUCCESSFULL = 'PROJECT_CREATED_DELETE_SUCCESSFULL'
export const PROJECT_CREATED_UPDATE_SUCCESSFULL = 'PROJECT_CREATED_UPDATE_SUCCESSFULL'
